work_dir: &work_dir logs/unseen_test
deterministic: False

data_dir: /path/to/AGD20K

load:
  encoder_ckpt: # leave blank for testing
  all_ckpt: /path/to/bestKLD.ckpt

batch_size: 10
img_size: 224
split_type: Unseen
num_exo: 1
PL_mode: refined
aug4imgRatio: 0.5

model:
  encoder_type: CLIP
  encoder_params:
    width: 768
    layers: 12
    heads: 12
    output_dim: 512
  decoder_embed_dim: 512

  pred_model_type: SAM
  pred_decoder_args:
    mlp_dim: 2048
    depth: 2
    use_up: 2
    use_additional_token: True
    conv_first: True

  margin: 0.1
