work_dir: &work_dir PL_refinement/logs/unseen_inf
deterministic: False

data_dir: /path/to/AGD20K # TODO
obj_mask_dir_name: whole_obj_mask_ego
save_name: unseen_refine_inference # TODO

pred_mask_temperature: 1.

load:
  encoder_ckpt: # leave blank for testing
  all_ckpt: PL_refinement/logs/unseen/ckpt/epoch10_aam.ckpt # TODO


img_size: 224
split_type: Unseen



model:
  encoder_type: CLIP
  encoder_params:
    width: 768
    layers: 12
    heads: 12
    output_dim: 512
  decoder_embed_dim: 512

  pred_model_type: SAM
  pred_decoder_args:
    mlp_dim: 2048
    depth: 2
    use_up: 2
    use_additional_token: True
    conv_first: True

  margin: 0.1


